app = "legacy-mv-api"
primary_region = "gru"

[build]

[env]
  PORT = "8080"
  FLASK_ENV = "production"
  FLASK_DEBUG = "False"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
